name = "1.21.1-Fabric"
author = "Crystal0404"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5e5e0305d97e3fbdc579a7100cbdea8eaca3e03a57061dc2922c719efce2396"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
